; espDisplay
; ESP8266 / Arduino / PlatformIO

[platformio]
default_envs = d1_mini

[env:d1_mini]
platform = espressif8266 @ 4.2.1
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 460800

build_flags =
  -Os
  -DPIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY

lib_deps =
  bblanchon/ArduinoJson @ 7.4.3
  https://github.com/avishorp/TM1637.git#v1.2.0
